[book]
authors = ["wukong"]
language = "zh-CN"
src = "src"
title = "galaxio-labs operator ecosystem"

[build]
build-dir = "book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/galaxio-labs/operator-docs"
additional-css = ["theme/site.css"]
additional-js = ["theme/site.js"]
