[book]
authors = ["wukong"]
language = "zh"
src = "./"
title = "galaxio-labs operator ecosystem"

[preprocessor.mermaid]
command = "mdbook-mermaid"


[output.html]
additional-css = ["./mermaid.css"]
additional-js = ["./mermaid.min.js"]
